version: "3.8"

services: 
  auth-service:
    build:
      context: .
      dockerfile: ./cmd/auth-service/Dockerfile
    environment:
      - DATABASE_URL=postgres://user:password@auth-db:5432/authdb?sslmode=disable
      - GRPC_PORT=50051
      - JWT_SECRET=6a9842f87acc69b6a4439be1f7585c23
    ports:
      - "50051:50051"
    restart: unless-stopped
    depends_on:
      - auth-db
    networks:
      - grpc-chat-network

  grpc-client:
    build:
      context: .
      dockerfile: ./cmd/grpc-client/Dockerfile
    depends_on:
      - auth-service
    networks:
      - grpc-chat-network
    command: ["-mode", "register", "-name", "testuser", "-password", "testpass"]

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - grpc-chat-network

volumes:
  db_data:

networks:
  grpc-chat-network:
